### ISSUE TITLE
Add Bisq exchange

### ISSUE THREAD

**Issue by mrosseel** [Bitcoin-Clashic/bitcoin-clashic.github.io#1]
Hi,

The Bisq exchange now supports Bitcoin Clashic and there are even 2 offers to buy online at the moment, so you could add it to the exchange list. Bisq only orchestrates the trade, it does not have a clashic wallet. As such, replay risks are to be mitigated by the users.

https://bisq.network

**Comment by cryptomeow** [comment]
Indeed thx. Just added it.
